### ISSUE TITLE
建议：优化待办

### ISSUE THREAD

**Issue by xiezhenxiang** [Demo-Liu/GeekDesk#41]
建议待办列表面板加个全局快捷键，不然想看待办列表时还要先打开主面板点下设置；
建议待办任务加个完成按钮、完成后的待办和未完成的待办加个样式区分、比如完成后的用中划线拉掉
建议新建待办可以选择不需要提醒、时间不是必填的

**Comment by Demo-Liu** [comment]
感谢建议, 后续会优化

**Comment by Demo-Liu** [comment]
> 建议待办列表面板加个全局快捷键，不然想看待办列表时还要先打开主面板点下设置； 建议待办任务加个完成按钮、完成后的待办和未完成的待办加个样式区分、比如完成后的用中划线拉掉 建议新建待办可以选择不需要提醒、时间不是必填的

建议已收到,  后续会优化这些内容
